name: Deploy to Xserver via SSH (Stage)
on:
  push:
    branches:
      - main
    paths:
      - 'Stage/**'

#####　GithubのSecrets and variableで設定
# SFTP_SERVE：Xserverのサーバー名（ホスト名）
# SFTP_USERNAME：XserverのSSHユーザー名
# SFTP_PRIVATE_KEY：ローカルで作成した秘密鍵の内容
# SFTP_TARGET：アップロード先ディレクトリ
####


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️ リポジトリをチェックアウト
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2️ Stage 中身を tar.gz にまとめる
      - name: Archive Stage contents
        run: tar -czf /tmp/Stage.tar.gz -C ./Stage .
        
      # 3️ tar.gz をサーバに転送
      - name: Upload Stage archive via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 10022
          source: "/tmp/Stage.tar.gz"
          target: "/roku-room.com/public_html/stage"

      # 4️ サーバ上で展開して tar.gz を削除
      - name: Extract archive on server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 10022
          script: |
                TARGET_DIR="/roku-room.com/public_html/stage"
                ls -l "$TARGET_DIR/tmp"
                tar -xzf "$TARGET_DIR/tmp/Stage.tar.gz" -C "$TARGET_DIR"
                rm /roku-room.com/public_html/stage/tmp/Stage.tar.gz
