name: Deploy to Xserver via SSH (Sneakers)
on:
  push:
    branches:
      - main
    paths:
      - 'Sneakers/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️ リポジトリをチェックアウト
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2️ Sneakers 中身を tar.gz にまとめる
      - name: Archive Sneakers contents
        run: tar -czf /tmp/Sneakers.tar.gz -C ./Sneakers .
        
      # 3️ tar.gz をサーバに転送
      - name: Upload Sneakers archive via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 10022
          source: "/tmp/Sneakers.tar.gz"
          target: ${{ secrets.SFTP_TARGET_SNEAKERS }}

      # 4️ サーバ上で展開して tar.gz を削除
      - name: Extract archive on server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 10022
          script: |
                TARGET_DIR="${{ secrets.SFTP_TARGET_SNEAKERS }}"
                ls -l "$TARGET_DIR/tmp"
                tar -xzf "$TARGET_DIR/tmp/Sneakers.tar.gz" -C "$TARGET_DIR"
                rm ${{ secrets.SFTP_TARGET_SNEAKERS }}/tmp/Sneakers.tar.gz
